export const tesla = {
  dealer_id: "",
  keyword: "",
  list_price_max: "",
  list_price_min: "",
  makes: ["tesla"],
  maximum_distance: "all",
  mileage_max: 50000,
  models: ["tesla-model_3"],
  page_size: 200,
  sort: "list_price",
  stock_type: "all",
  trims: ["tesla-model_3-performance"],
  year_max: "2020",
  year_min: "",
  zip: 27599,
};
